ReadMe.md updated
KingsleyMcSimon/appleclone pull request #3
Opened 2019-09-06 17:44 UTC by KingsleyMcSimon

2019-09-07 01:10 UTC, uche-inyama requested changes
## Hi Kingsley you have made good progress :raised_hands: 

### But there are changes to be made
- [ ] There are no stickler checks on this project, please ensure there is, and it passes  the checks.
- [ ] Use these snap shots as a reference to update your project. These are my observations.
   * The navigation bar is not properly aligned.
   * The links on the footer are also not properly aligned.

The first two images are yours, compare it with the last two from apple.com

![Screenshot from 2019-09-07 01-57-32](https://user-images.githubusercontent.com/46329537/64467767-d6cf3b80-d113-11e9-961d-1edb19788b9a.png)

![Screenshot from 2019-09-07 01-58-37](https://user-images.githubusercontent.com/46329537/64467777-fe260880-d113-11e9-9c81-0a0c656283b8.png)


![Screenshot from 2019-09-07 01-58-41](https://user-images.githubusercontent.com/46329537/64467830-bfdd1900-d114-11e9-996a-498334387fbf.png)

![Screenshot from 2019-09-07 01-58-41](https://user-images.githubusercontent.com/46329537/64467835-d1bebc00-d114-11e9-8614-aa0aefc91054.png)

### Kindly implement these changes and submit another code review form. :muscle:

2020-05-29 00:54 UTC, KingsleyMcSimon commented
This is really an old project, I have actually reviewed it as it is expected of me and the changes done can be seen at the Readme branch of the project.

2020-05-29 01:47 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-29 01:47 UTC, lucasmazo32 commented on index.html
>              <li><i class="fa fa-apple" aria-hidden="true"></i></li>
- [ ] The gradient is slightly different. Kindly fix that.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83212066-3c40dd80-a124-11ea-85a6-c5e9b4b10382.png) | ![image](https://user-images.githubusercontent.com/57414789/83212079-44008200-a124-11ea-96dc-dbe00e02c3cc.png)

2020-05-29 01:47 UTC, lucasmazo32 commented on .stickler.yml
> +linters:
- [ ] Kindly enable the stickler for this repo. You will have to go to https://stickler-ci.com/ to do so.

2020-05-29 21:14 UTC, KingsleyMcSimon commented
The required changes has been implemented and the project has passed all the stickler test.

2020-05-30 01:46 UTC, trekab requested changes
# Changes Required! :recycle: 
Hi @KingsleyMcSimon, great job so far! There are a few changes to make to complete this project.

- [ ] You still have [HTML validator](https://validator.w3.org/#validate_by_upload) errors. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
- [ ] Your footer appears to be more to the left. Try to center it more, to make it appear like the original site's footer.

__N.B:__ Checkout [Professional Github repository guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for your next projects to keep your repositories professional. Apparently your pull request has no summary. 

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__

2020-05-31 00:50 UTC, KingsleyMcSimon commented
Readme Branch:
As required, the html validator check have been passed.
Proper footer styling implemented.
All the stickler error check passed.

2020-05-31 02:44 UTC, sumancrest0001 approved these changes
# Congratulations @KingsleyMcSimon :fire: :clap: :100: 
You ticked all the minimal requirements from the project specifications. The layout looks similar to the original one, and stickler is passing with no HTML validator error. Now, you can merge the branch to master.

**Best of luck for the next project.
Happy coding !!!!**

2020-05-31 21:28 UTC, merged